apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: lt
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: lt
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/min-scale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
  source:
    git:
      url: https://github.com/tfynes-pivotal/lt
      ref:
        branch: main
  serviceClaims:
  - name: p1
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: p1
